name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update vql
      run: |
        pwd
        cd ./scripts
        for x in ${{ ls *.py }}; do
          python3 $i
        done
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}        
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating VQL"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master        
    - name: Zip Folder
      run: zip -r DetectRaptorVQL.zip vql/*.yaml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: DetectRaptorVQL.zip
        tag: DetectRaptor
        allowUpdates: true
