name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r DetectRaptorVQL.zip vql/*.yaml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: DetectRaptorVQL.zip
        tag: DetectRaptor
        allowUpdates: true
