name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update vql
      run: |
        pwd
        cd ./scripts
        for x in $( ls *.py ); do
          python3 $i
        done
        cd ..      
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated VQL update
        commit_options: '--no-verify --signoff'
        file_pattern: 'vql/*.yaml'
        repository: .

        # Optional commit user and author settings
        commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
        commit_user_email: my-github-actions-bot@dfir.au
        status_options: '--untracked-files=no'
        skip_checkout: true    
    
    - name: Zip Folder
      run: zip -r DetectRaptorVQL.zip vql/*.yaml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: DetectRaptorVQL.zip
        tag: DetectRaptor
        allowUpdates: true
