name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Self test
      id: selftest
      uses: ryan-rozario/pipreqs-action-cpy@master
      # Put an example of mandatory inputs here
      with:
        PROJECT_PATH: .
        REQUIREMENT_PATH: ./requirements.txt
    
    - name: Update vql
      run: |
          pip install -f ./requirements.txt
          cd ./scripts
          for x in $( ls *.py ); do
            /usr/bin/python $i
          done 
          cd ..
          echo $(shasum vql/*.yaml)
          cat ./requirements.txt
          
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: AutoUpdate VQL
        
    - name: Zip Folder
      run: zip -r DetectRaptorVQL.zip vql/*.yaml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: DetectRaptorVQL.zip
        tag: DetectRaptor
        allowUpdates: true
