name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
          
    - name: Update vql
      run: |
          pip install PyYAML==6.0 -q
          cd ./scripts
          python bulk_mft.py
          python bulk_evtx.py
          cd ..
          echo $(shasum vql/*.yaml)
          
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: AutoUpdate VQL
        
    - name: Zip Folder
      run: zip -r DetectRaptorVQL.zip vql/*.yaml
    - uses: ncipollo/release-action@v1
      with:
        artifacts: DetectRaptorVQL.zip
        tag: DetectRaptor
        allowUpdates: true
